# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  aspcore-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster

jobs: 
  example1:
    machine:
      image: aspcore-executor
    steps:
      - run:
          name: "echo environment variables from org-global context"
          command: echo $MY_SECRET_VAR
  example2:
    machine:
      image: aspcore-executor
    steps:
      - run:
          name: "echo environment variables from org-global context"
          command: echo $MY_SECRET_VAR

workflows:
  build_job:
    jobs:
      - example1:
          context:
            - my-secrets
      - example2:
          requires: 
              - example1
